### POST Register a User Test Route
POST {{ BASE_URL }}/api/auth/register
Content-Type: application/json

{
  "email": "testuser61@uwindsor.ca",
  "password": "newPassword@123",
  "password_confirmation": "newPassword@123"
}

### POST Logging in a User Test Route
POST {{ BASE_URL }}/api/auth/login
Content-Type: application/json

{
  "email": "testuser5@uwindsor.ca",
  "password": "newPassword@123"
}

### POST Resending a verification email
POST {{ BASE_URL }}/api/auth/resend-verification
Content-Type: application/json

{
  "email": "email8@uwindsor.ca"
}

### GET Verify a user token for email verification
GET {{ BASE_URL }}/api/auth/verify-email
Content-Type: application/json

{
  "id": "59fe1392-775a-4976-bb26-f8487f182ddf",
  "otpCode": "748404"
}

### POST Send a password reset email
POST {{ BASE_URL }}/api/auth/request-password-reset
Content-Type: application/json

{
  "email": "user4@uwindsor.ca"
}

### POST Verify password reset OTP
POST {{ BASE_URL }}/api/auth/verify-reset-otp
Content-Type: application/json

{
  "email": "user4@uwindsor.ca",
  "otp": "427907"
}

### POST Reset password
POST {{ BASE_URL }}/api/auth/reset-password
Content-Type: application/json

{
  "userId": "0cbff286-c6d7-47ae-93cf-e070138a9a65",
  "password": "neewPassword#1244444",
  "password_confirmation": "neewPassword#1244444"
}




### POST Create a profile
POST {{ BASE_URL }}/api/profiles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5ZmUxMzkyLTc3NWEtNDk3Ni1iYjI2LWY4NDg3ZjE4MmRkZiIsImVtYWlsIjoidGVzdHVzZXI1QHV3aW5kc29yLmNhIiwiaWF0IjoxNzY5MTI5OTIzLCJleHAiOjE3NjkxMzE3MjN9.XjX7x2-RtXzuZzYRBHXp0SrhQLTtt-3j1MsQgj3qkpw
Content-Type: application/json

{
  "name": "User 5",
  "bio": "Second year CS student interested in tutoring COMP classes.",
  "major": "Computer Science",
  "yearOfStudy": 2,

  "isTutor": true,
  "isTutee": true,

  "tutorCourseIds": [1, 3, 5],
  "tuteeCourseIds": [91, 124],

  "availability": [
    { "day": "TUE", "startMin": 540, "endMin": 660 },
    { "day": "THU", "startMin": 840, "endMin": 960 }
  ]
}

### GET a users information (ME)
GET {{ BASE_URL }}/api/profiles/me
Authorization: Bearer Bearer TOKEN_HERE

### PUT update a users profile
PUT {{ BASE_URL }}/api/profiles/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5ZmUxMzkyLTc3NWEtNDk3Ni1iYjI2LWY4NDg3ZjE4MmRkZiIsImVtYWlsIjoidGVzdHVzZXI1QHV3aW5kc29yLmNhIiwiaWF0IjoxNzY5MTg3MjM4LCJleHAiOjE3NjkxODkwMzh9.zWtevYglZlw8R8kIVFxqW0BuLiNytpCoUh18oabCrfU
Content-Type: application/json

{
  "name": "Linus Torvald",
  "bio": "Third year CS student interested in tutoring COMP classes.",
  "major": "Computer Science",
  "yearOfStudy": 3,

  "isTutor": true,
  "isTutee": true,

  "tutorCourseIds": [6, 7, 8],
  "tuteeCourseIds": [23, 26],

  "availability": [
    { "day": "WED", "startMin": 600, "endMin": 710 },
    { "day": "FRI", "startMin": 900, "endMin": 1020 }
  ]
}




### POST create a thread
POST {{ BASE_URL }}/api/threads
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5ZmUxMzkyLTc3NWEtNDk3Ni1iYjI2LWY4NDg3ZjE4MmRkZiIsImVtYWlsIjoidGVzdHVzZXI1QHV3aW5kc29yLmNhIiwiaWF0IjoxNzY5MTg3MjM4LCJleHAiOjE3NjkxODkwMzh9.zWtevYglZlw8R8kIVFxqW0BuLiNytpCoUh18oabCrfU
Content-Type: application/json

{
  "participant1": "2c9694bd-7b02-4b8d-b97a-5d66c603bcc6",
  "participant2": "59fe1392-775a-4976-bb26-f8487f182ddf"
}

### GET a user's threads
GET {{ BASE_URL }}/api/threads/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5ZmUxMzkyLTc3NWEtNDk3Ni1iYjI2LWY4NDg3ZjE4MmRkZiIsImVtYWlsIjoidGVzdHVzZXI1QHV3aW5kc29yLmNhIiwiaWF0IjoxNzY5MTg3MjM4LCJleHAiOjE3NjkxODkwMzh9.zWtevYglZlw8R8kIVFxqW0BuLiNytpCoUh18oabCrfU
Content-Type: application/json


### POST Create a message
POST {{ BASE_URL }}/api/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5ZmUxMzkyLTc3NWEtNDk3Ni1iYjI2LWY4NDg3ZjE4MmRkZiIsImVtYWlsIjoidGVzdHVzZXI1QHV3aW5kc29yLmNhIiwiaWF0IjoxNzY5MTg3MjM4LCJleHAiOjE3NjkxODkwMzh9.zWtevYglZlw8R8kIVFxqW0BuLiNytpCoUh18oabCrfU
Content-Type: application/json

{
  "threadId": "d63d1932-5d00-4030-9ea4-04ce093a1d1d",
  "senderId": "b2556edd-4767-471e-a5e4-46156d636ecc",
  "content": "Hi"
}

### GET Get messaegs from thread
GET {{ BASE_URL }}/api/messages/d63d1932-5d00-4030-9ea4-04ce093a1d1d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5ZmUxMzkyLTc3NWEtNDk3Ni1iYjI2LWY4NDg3ZjE4MmRkZiIsImVtYWlsIjoidGVzdHVzZXI1QHV3aW5kc29yLmNhIiwiaWF0IjoxNzY5MTg3MjM4LCJleHAiOjE3NjkxODkwMzh9.zWtevYglZlw8R8kIVFxqW0BuLiNytpCoUh18oabCrfU
Content-Type: application/json

