### POST Register a User Test Route
POST {{ BASE_URL }}/api/auth/register
Content-Type: application/json

{
  "email": "evanproulx1@uwindsor.ca",
  "password": "newPassword@123",
  "password_confirmation": "newPassword@123"
}

### POST Logging in a User Test Route
POST {{ BASE_URL }}/api/auth/login
Content-Type: application/json

{
  "email": "evanproulx1@uwindsor.ca",
  "password": "newPassword@123"
}

### POST Resending a verification email
POST {{ BASE_URL }}/api/auth/resend-verification
Content-Type: application/json

{
  "email": "evanproulx@uwindsor.ca"
}

### POST Send a password reset email
POST {{ BASE_URL }}/api/auth/request-password-reset
Content-Type: application/json

{
  "email": "evanproulx@uwindsor.ca"
}


### GET Verify a user token for email verification
GET {{ BASE_URL }}/api/auth/verify-email
Content-Type: application/json

{
  "id": "fdfbb4e8-1802-4534-b767-17f6d254656c",
  "otpCode": "590809"
}
