### POST Register a User Test Route
POST {{ BASE_URL }}/api/auth/register
Content-Type: application/json

{
  "email": "baidwant@uwindsor.ca",
  "password": "newPassword@123",
  "password_confirmation": "newPassword@123"
}

### POST Logging in a User Test Route
POST {{ BASE_URL }}/api/auth/login
Content-Type: application/json

{
  "email": "baidwant@uwindsor.ca",
  "password": "newPassword@123"
}